default:
  image: node:20

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - node -v
    - npm -v
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Tests passed. Ready for deployment."